build:
  version_from_profile: ${build.version}
  default_version: "{cipher}5e0a912c98a022f16a500cf05bbd2d79dee464554b1637ece5ea4ad9ae11e206"
  duplicated_version: "a dup default" # hadi w li lfo9 kamlin ayakhod card machi app
  version_from_profile2: ${build.version2}
  default_version2: "a default"
  duplicated_version2: "a dup default"


server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card_db
    username: postgres
    password: cardpw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
